[package]
name = "bevy-orbit-camera"
version = "0.1.0"
authors = ["super-tuple"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4" 
derive_builder = "0.9.0"